[project]
name = "arxiv-daily-digest-frontend"
version = "0.0.1"
description = "Streamlit UI"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "streamlit>=1.53.0",
]
