services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_started
      qdrant:
        condition: service_started
    env_file: .env
    environment:
      - MONGO_URI=mongodb://${MONGO_USER:-admin}:${MONGO_PASS:-pass}@mongo:27017
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - arxiv_net
    
    # dev settings
    # tty: true
    # stdin_open: true
    # command: sleep infinity

  mongo:
    image: mongo:7.0
    container_name: arxiv_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-pass}
    volumes:
      - ./data/mongo_db:/data/db
    networks:
      - arxiv_net

  qdrant:
    image: qdrant/qdrant:latest
    container_name: arxiv_qdrant
    restart: always
    volumes:
      - ./data/qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
    networks:
      - arxiv_net

networks:
  arxiv_net:
    driver: bridge